/**
 * Built-in pixel asset manifest
 *
 * Defines the canonical sprite metadata for all built-in plant species,
 * growth stages, plant health states, terrain tiles, creatures, and visual effects.
 */

import { createAnimation } from "./animation.js";
import type { PlantSpriteMetadata, SpriteMetadata, TileSpriteMetadata } from "./types.js";

// Standard anchor points
const ANCHOR_BOTTOM_CENTER = { x: 0.5, y: 1.0 } as const;
const ANCHOR_TOP_LEFT = { x: 0.0, y: 0.0 } as const;
const ANCHOR_CENTER = { x: 0.5, y: 0.5 } as const;

// ─── Plant Sprites ────────────────────────────────────────────────────────────

export const BUILTIN_PLANT_SPRITES: readonly PlantSpriteMetadata[] = [
  // ─── Oak Tree ───────────────────────────────────────────────────────────────
  {
    id: "oak.SEED",
    type: "plant",
    speciesId: "oak",
    growthStage: "SEED",
    spriteSheet: "plants.png",
    frame: 0,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "oak.SPROUT",
    type: "plant",
    speciesId: "oak",
    growthStage: "SPROUT",
    spriteSheet: "plants.png",
    frame: 1,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "oak.YOUNG",
    type: "plant",
    speciesId: "oak",
    growthStage: "YOUNG",
    spriteSheet: "plants.png",
    frame: 2,
    width: 16,
    height: 24,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "oak.MATURE",
    type: "plant",
    speciesId: "oak",
    growthStage: "MATURE",
    spriteSheet: "plants.png",
    frame: 3,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
    animations: {
      idle: createAnimation("idle", [3, 4], 400),
    },
  },
  {
    id: "oak.MATURE.WILTED",
    type: "plant",
    speciesId: "oak",
    growthStage: "MATURE",
    health: "WILTED",
    spriteSheet: "plants.png",
    frame: 9,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "oak.MATURE.DORMANT",
    type: "plant",
    speciesId: "oak",
    growthStage: "MATURE",
    health: "DORMANT",
    spriteSheet: "plants.png",
    frame: 10,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "oak.FLOWERING",
    type: "plant",
    speciesId: "oak",
    growthStage: "FLOWERING",
    spriteSheet: "plants.png",
    frame: 5,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
    animations: {
      idle: createAnimation("idle", [5, 6], 400),
    },
  },
  {
    id: "oak.FLOWERING.WILTED",
    type: "plant",
    speciesId: "oak",
    growthStage: "FLOWERING",
    health: "WILTED",
    spriteSheet: "plants.png",
    frame: 11,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "oak.FLOWERING.DORMANT",
    type: "plant",
    speciesId: "oak",
    growthStage: "FLOWERING",
    health: "DORMANT",
    spriteSheet: "plants.png",
    frame: 12,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "oak.SPECIAL",
    type: "plant",
    speciesId: "oak",
    growthStage: "SPECIAL",
    spriteSheet: "plants.png",
    frame: 7,
    width: 32,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
    animations: {
      idle: createAnimation("idle", [7, 8], 450),
    },
  },

  // ─── Cherry Blossom ────────────────────────────────────────────────────────
  {
    id: "cherry.SEED",
    type: "plant",
    speciesId: "cherry",
    growthStage: "SEED",
    spriteSheet: "plants.png",
    frame: 20,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cherry.SPROUT",
    type: "plant",
    speciesId: "cherry",
    growthStage: "SPROUT",
    spriteSheet: "plants.png",
    frame: 21,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cherry.YOUNG",
    type: "plant",
    speciesId: "cherry",
    growthStage: "YOUNG",
    spriteSheet: "plants.png",
    frame: 22,
    width: 16,
    height: 24,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cherry.MATURE",
    type: "plant",
    speciesId: "cherry",
    growthStage: "MATURE",
    spriteSheet: "plants.png",
    frame: 23,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
    animations: {
      idle: createAnimation("idle", [23, 24], 400),
    },
  },
  {
    id: "cherry.MATURE.WILTED",
    type: "plant",
    speciesId: "cherry",
    growthStage: "MATURE",
    health: "WILTED",
    spriteSheet: "plants.png",
    frame: 27,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cherry.MATURE.DORMANT",
    type: "plant",
    speciesId: "cherry",
    growthStage: "MATURE",
    health: "DORMANT",
    spriteSheet: "plants.png",
    frame: 28,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cherry.FLOWERING",
    type: "plant",
    speciesId: "cherry",
    growthStage: "FLOWERING",
    spriteSheet: "plants.png",
    frame: 25,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
    animations: {
      idle: createAnimation("idle", [25, 26], 400),
    },
  },
  {
    id: "cherry.FLOWERING.WILTED",
    type: "plant",
    speciesId: "cherry",
    growthStage: "FLOWERING",
    health: "WILTED",
    spriteSheet: "plants.png",
    frame: 29,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cherry.FLOWERING.DORMANT",
    type: "plant",
    speciesId: "cherry",
    growthStage: "FLOWERING",
    health: "DORMANT",
    spriteSheet: "plants.png",
    frame: 30,
    width: 24,
    height: 32,
    anchor: ANCHOR_BOTTOM_CENTER,
  },

  // ─── Mushroom ──────────────────────────────────────────────────────────────
  {
    id: "mushroom.SEED",
    type: "plant",
    speciesId: "mushroom",
    growthStage: "SEED",
    spriteSheet: "plants.png",
    frame: 40,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "mushroom.SPROUT",
    type: "plant",
    speciesId: "mushroom",
    growthStage: "SPROUT",
    spriteSheet: "plants.png",
    frame: 41,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "mushroom.MATURE",
    type: "plant",
    speciesId: "mushroom",
    growthStage: "MATURE",
    spriteSheet: "plants.png",
    frame: 42,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "mushroom.MATURE.WILTED",
    type: "plant",
    speciesId: "mushroom",
    growthStage: "MATURE",
    health: "WILTED",
    spriteSheet: "plants.png",
    frame: 44,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "mushroom.MATURE.DORMANT",
    type: "plant",
    speciesId: "mushroom",
    growthStage: "MATURE",
    health: "DORMANT",
    spriteSheet: "plants.png",
    frame: 45,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "mushroom.SPECIAL",
    type: "plant",
    speciesId: "mushroom",
    growthStage: "SPECIAL",
    spriteSheet: "plants.png",
    frame: 43,
    width: 24,
    height: 24,
    anchor: ANCHOR_BOTTOM_CENTER,
    animations: {
      idle: createAnimation("idle", [43, 46], 500),
    },
  },

  // ─── Cactus ────────────────────────────────────────────────────────────────
  {
    id: "cactus.SEED",
    type: "plant",
    speciesId: "cactus",
    growthStage: "SEED",
    spriteSheet: "plants.png",
    frame: 60,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cactus.YOUNG",
    type: "plant",
    speciesId: "cactus",
    growthStage: "YOUNG",
    spriteSheet: "plants.png",
    frame: 61,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cactus.MATURE",
    type: "plant",
    speciesId: "cactus",
    growthStage: "MATURE",
    spriteSheet: "plants.png",
    frame: 62,
    width: 16,
    height: 24,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cactus.MATURE.WILTED",
    type: "plant",
    speciesId: "cactus",
    growthStage: "MATURE",
    health: "WILTED",
    spriteSheet: "plants.png",
    frame: 64,
    width: 16,
    height: 24,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cactus.MATURE.DORMANT",
    type: "plant",
    speciesId: "cactus",
    growthStage: "MATURE",
    health: "DORMANT",
    spriteSheet: "plants.png",
    frame: 65,
    width: 16,
    height: 24,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cactus.FLOWERING",
    type: "plant",
    speciesId: "cactus",
    growthStage: "FLOWERING",
    spriteSheet: "plants.png",
    frame: 63,
    width: 16,
    height: 24,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cactus.FLOWERING.WILTED",
    type: "plant",
    speciesId: "cactus",
    growthStage: "FLOWERING",
    health: "WILTED",
    spriteSheet: "plants.png",
    frame: 66,
    width: 16,
    height: 24,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "cactus.FLOWERING.DORMANT",
    type: "plant",
    speciesId: "cactus",
    growthStage: "FLOWERING",
    health: "DORMANT",
    spriteSheet: "plants.png",
    frame: 67,
    width: 16,
    height: 24,
    anchor: ANCHOR_BOTTOM_CENTER,
  },

  // ─── Wildflower ─────────────────────────────────────────────────────────────
  {
    id: "flower.SEED",
    type: "plant",
    speciesId: "flower",
    growthStage: "SEED",
    spriteSheet: "plants.png",
    frame: 80,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "flower.SPROUT",
    type: "plant",
    speciesId: "flower",
    growthStage: "SPROUT",
    spriteSheet: "plants.png",
    frame: 81,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "flower.FLOWERING",
    type: "plant",
    speciesId: "flower",
    growthStage: "FLOWERING",
    spriteSheet: "plants.png",
    frame: 82,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
    animations: {
      idle: createAnimation("idle", [82, 83], 350),
    },
  },
  {
    id: "flower.FLOWERING.WILTED",
    type: "plant",
    speciesId: "flower",
    growthStage: "FLOWERING",
    health: "WILTED",
    spriteSheet: "plants.png",
    frame: 84,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
  {
    id: "flower.FLOWERING.DORMANT",
    type: "plant",
    speciesId: "flower",
    growthStage: "FLOWERING",
    health: "DORMANT",
    spriteSheet: "plants.png",
    frame: 85,
    width: 16,
    height: 16,
    anchor: ANCHOR_BOTTOM_CENTER,
  },
];

// ─── Terrain Tile Sprites ─────────────────────────────────────────────────────

export const BUILTIN_TILE_SPRITES: readonly TileSpriteMetadata[] = [
  {
    id: "tile.GRASS",
    type: "tile",
    variant: "GRASS",
    spriteSheet: "terrain.png",
    frame: 0,
    width: 16,
    height: 16,
    anchor: ANCHOR_TOP_LEFT,
  },
  {
    id: "tile.SOIL",
    type: "tile",
    variant: "SOIL",
    spriteSheet: "terrain.png",
    frame: 1,
    width: 16,
    height: 16,
    anchor: ANCHOR_TOP_LEFT,
  },
  {
    id: "tile.PATH",
    type: "tile",
    variant: "PATH",
    spriteSheet: "terrain.png",
    frame: 2,
    width: 16,
    height: 16,
    anchor: ANCHOR_TOP_LEFT,
  },
  {
    id: "tile.WATER",
    type: "tile",
    variant: "WATER",
    spriteSheet: "terrain.png",
    frame: 3,
    width: 16,
    height: 16,
    anchor: ANCHOR_TOP_LEFT,
    animations: {
      flow: createAnimation("flow", [3, 4], 500),
    },
  },
  {
    id: "tile.STONE",
    type: "tile",
    variant: "STONE",
    spriteSheet: "terrain.png",
    frame: 5,
    width: 16,
    height: 16,
    anchor: ANCHOR_TOP_LEFT,
  },
];

// ─── Creatures & Visual Effects ───────────────────────────────────────────────

export const BUILTIN_OTHER_SPRITES: readonly SpriteMetadata[] = [
  {
    id: "creature.butterfly",
    type: "creature",
    spriteSheet: "creatures.png",
    frame: 0,
    width: 16,
    height: 16,
    anchor: ANCHOR_CENTER,
    animations: {
      fly: createAnimation("fly", [0, 1], 150),
    },
  },
  {
    id: "creature.firefly",
    type: "creature",
    spriteSheet: "creatures.png",
    frame: 2,
    width: 8,
    height: 8,
    anchor: ANCHOR_CENTER,
    animations: {
      glow: createAnimation("glow", [2, 3], 350),
    },
  },
  {
    id: "effect.SPARKLE",
    type: "effect",
    spriteSheet: "effects.png",
    frame: 0,
    width: 16,
    height: 16,
    anchor: ANCHOR_CENTER,
    animations: {
      sparkle: createAnimation("sparkle", [0, 1, 2], 100, false),
    },
  },
  {
    id: "effect.LEAF_DRIFT",
    type: "effect",
    spriteSheet: "effects.png",
    frame: 3,
    width: 16,
    height: 16,
    anchor: ANCHOR_CENTER,
    animations: {
      drift: createAnimation("drift", [3, 4, 5], 200),
    },
  },
];

// ─── Combined Built-in Manifest ───────────────────────────────────────────────

export const BUILTIN_SPRITES: readonly SpriteMetadata[] = [
  ...BUILTIN_PLANT_SPRITES,
  ...BUILTIN_TILE_SPRITES,
  ...BUILTIN_OTHER_SPRITES,
];
